### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by uchicom** [uchicom/smtp#6]
# 要件
特定のメールが届いた場合に、webhook通知したい

# 設計
- webhook用の設定ファイルを追加する。.webhook.ymlファイルに変更する。
- メール文面や、件名から条件を抽出し、webhookへリクエストする
## .smtp.yml設定
yml形式
```
send:
  method: POST
  url: https://dokosoko/sample/api/webhook/hoge
  header:
    Content-Type: application/json
    Webhook-Token: smtp_webhook_0123456789
  body:
    template: {title:"${subject}", content:"${content:1}"} // :1を指定するとmatch
    parameter:
      a: 
        target: subject
        pattern: ^abc$
      b: // 括弧を
        target: content
        pattern: ^abc(def)gh$
  query: // urlの後ろにつけるやつ まだ対応しない
    ... // bodyと同じ形式
detection: // 配列はorで
  - subject: and 条件
    header: string string map
      Content-Type: multipart/alternative;
    multipart:
      contntType: text/plain; charset=UTF-8
      body:
    from: dokosoko@mail.com
    to: to@dokosoko.com
    cc:
    bcc:
  - subject:
    header: 
      Content-Type: text/plain; charset=UTF-8
    content:
    from:
    to:
    cc:
```

#### 送信時の条件
GET or POST  

content-type  
bodyテンプレート   
json なら {"hoge":"${a:1}","hoge2":"${b:2}"}  
のように指定すると、本文から抽出して設定する。  
postパラメータなら  
hoge=${a:1}&hoge2=${b:2}  
getのqueryパラメータ  
?hoge=${a:1}&hoge2=${b:2}  
↑いまは対応しない。  

Java11のHttpClientを利用する。
そのためwebhookを利用するためにはjava11以上
smtpはjava20で作成する

- webhookエラーがあった場合は、どこかにエラーを通知できるようにしたい。エラー送信情報も必要。いまは対応しない
